### ISSUE TITLE
1.10 Forge essentials

### ISSUE THREAD

**Issue by gigafunk** [ate47/AutoLoginMod#1]
Hello!   Forge essentials just came out and the y have an auth mod.

But its commands are 

/auth register
/auth login

so it doesnt work with your cool lil mod.

Im gonna try to hack at it, is this the most up to date github for the 1.10 version?

of course feel free to help me out with it, but i might be able to do it .

Provided this is the repository for 1.10.2 .

thanks!

juyst tried, realize I have no ide how to build this without gradle. lol  

SO this is great, but a little nonflexible. if you had maybe a setup file to chose the register command and what string it looks for to decide , that would be cool.

if not a little tip on what i should be looking into to build it and ill try to hard code it myself.
Thanks againA

Can you share an updated github so I can customize the strings it looks for?  I am trying to stop it from firing off everytime i use the help menu and /login and /register appear in my chat window.  I can do it and build it, I just need the 1.10 source. Thanks!

**Comment by ate47** [comment]
done in 2.0
