### ISSUE TITLE
1.12.2 Crash....

### ISSUE THREAD

**Issue by Vizis** [ate47/AutoLoginMod#2]
forge              | 14.23.2.2611 
spongeforge-1.12.2-2586-7.1.0-BETA-2900

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Auto Login Mod (autologin)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen

**Comment by ate47** [comment]
net/minecraft/client/gui/GuiScreen is a Minecraft class
